//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myBookSolution.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myBookSolution.Exceptions.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O autor informado não está cadastrado no sistema..
        /// </summary>
        public static string AUTOR_INFORMADO_NAO_EXISTE {
            get {
                return ResourceManager.GetString("AUTOR_INFORMADO_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O autor já está cadastrado..
        /// </summary>
        public static string AUTOR_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("AUTOR_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de nome do autor não pode ser vazio..
        /// </summary>
        public static string BUSCA_AUTOR_VAZIO {
            get {
                return ResourceManager.GetString("BUSCA_AUTOR_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os campos de busca não podem ser vazios..
        /// </summary>
        public static string CAMPO_BUSCA_VAZIO {
            get {
                return ResourceManager.GetString("CAMPO_BUSCA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CPF válido..
        /// </summary>
        public static string CPF_INCORRETO {
            get {
                return ResourceManager.GetString("CPF_INCORRETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com o CPF informado..
        /// </summary>
        public static string CPF_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um curador registrado com o CPF informador..
        /// </summary>
        public static string CPF_JA_REGISTRADO_CURADOR {
            get {
                return ResourceManager.GetString("CPF_JA_REGISTRADO_CURADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há usuário cadastrado com o CPF informado..
        /// </summary>
        public static string CPF_USUARIO_NAO_EXISTE {
            get {
                return ResourceManager.GetString("CPF_USUARIO_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira a descrição do autor..
        /// </summary>
        public static string DESCRICAO_AUTOR_VAZIA {
            get {
                return ResourceManager.GetString("DESCRICAO_AUTOR_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição do livro não pode ser vazia..
        /// </summary>
        public static string DESCRICAO_LIVRO_VAZIA {
            get {
                return ResourceManager.GetString("DESCRICAO_LIVRO_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize um endereço email válido..
        /// </summary>
        public static string EMAIL_INCORRETO {
            get {
                return ResourceManager.GetString("EMAIL_INCORRETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário registrado com o email informado..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um curador registrado com o email informado..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO_CURADOR {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO_CURADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e/ou senha incorreto(s)..
        /// </summary>
        public static string EMAIL_OU_SENHA_INCORRETOS {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INCORRETOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode ser vazio..
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível cadastrar o empréstimo..
        /// </summary>
        public static string ERRO_EMPRESTIMO {
            get {
                return ResourceManager.GetString("ERRO_EMPRESTIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de livros deve ser maior que 0..
        /// </summary>
        public static string ESTOQUE_INCORRETO {
            get {
                return ResourceManager.GetString("ESTOQUE_INCORRETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um livro cadastrado com o mesmo ISBN..
        /// </summary>
        public static string ISBN_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("ISBN_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há livro cadastrado com o ISBN informado..
        /// </summary>
        public static string ISBN_LIVRO_NAO_EXISTE {
            get {
                return ResourceManager.GetString("ISBN_LIVRO_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ISBN nao pode ser vazio..
        /// </summary>
        public static string ISBN_VAZIO {
            get {
                return ResourceManager.GetString("ISBN_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um livro de mesmo nome já está cadastrado..
        /// </summary>
        public static string LIVRO_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("LIVRO_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o ISBN do livro (COM HÍFENS) para cadastrar o empréstimo..
        /// </summary>
        public static string LIVRO_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("LIVRO_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No momento, não há cópia disponível do livro solicitado..
        /// </summary>
        public static string LIVRO_SEM_ESTOQUE {
            get {
                return ResourceManager.GetString("LIVRO_SEM_ESTOQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira o nome do autor..
        /// </summary>
        public static string NOME_AUTOR_VAZIO {
            get {
                return ResourceManager.GetString("NOME_AUTOR_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser vazio..
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve erro na autenticação..
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter 6 ou mais caracteres..
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua sessão foi expirada. .
        /// </summary>
        public static string SESSAO_EXPIRADA {
            get {
                return ResourceManager.GetString("SESSAO_EXPIRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O título do livro não pode ser vazio..
        /// </summary>
        public static string TITULO_LIVRO_VAZIO {
            get {
                return ResourceManager.GetString("TITULO_LIVRO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu token de acesso expirou..
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF do usuário (SOMENTE NÚMEROS) deve ser informado para cadastrar o empréstimo. .
        /// </summary>
        public static string USUARIO_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado não pode realizar empréstimos até devolver o livro que pegou anteriormente..
        /// </summary>
        public static string USUARIO_PENDENCIAS {
            get {
                return ResourceManager.GetString("USUARIO_PENDENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não tem empréstimo ativo..
        /// </summary>
        public static string USUARIO_SEM_EMPRESTIMO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_EMPRESTIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não tem permissão para acessar esse recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
            }
        }
    }
}
